### ISSUE TITLE
Estrutura cicloviária georeferenciada

### ISSUE THREAD

**Issue by biketrooper** [CodeForCuritiba/dadosabertos_prefs#10]
Gostaríamos de informações em formato digital, se possível georeferenciada das ciclovias, ciclofaixas, ciclorrotas, conjunto de paraciclos, existentes e previstos em projetos da Prefeitura, IPPUC, SETRAN #

**Comment by thierrydelbart** [comment]
Legal @biketrooper . Eu vou avisar Bruno da pref para ir atrás.

**Comment by brunoglara** [comment]
Boa tarde,
Quais os formatos dos arquivos necessários para reutilização?

**Comment by biketrooper** [comment]
Acho que o ideal seria [GeoJSON](http://geojson.org):
GeoJSON is a format for encoding a variety of geographic data structures. A GeoJSON object may represent a geometry, a feature, or a collection of features. GeoJSON supports the following geometry types: Point, LineString, Polygon, MultiPoint, MultiLineString, MultiPolygon, and GeometryCollection. Features in GeoJSON contain a geometry object and additional properties, and a feature collection represents a list of features.

Caso não seja possível, KML, XML, CSV...

**Comment by thierrydelbart** [comment]
Isso, acho que GeoJSON é o mais eficiente. Mas KML também é um padrão interessante.

**Comment by brunoglara** [comment]
Bom dia,
Entrei em contato com o IPPUC e eles me passaram esta URL:
http://ippuc.org.br/geodownloads/geo.htm
Eles informaram que os dados de ciclorotas e ciclovias já estão em formatos para serem reutilizados ou convertidos. Peço que verifiquem e qualquer coisa me avise.

Atenciosamente
Bruno

**Comment by thierrydelbart** [comment]
Oi @brunoglara,
Dei uma olhada.
Duas perguntas:
- é com esses arquivos ZIP que a prefeitura manda para o google as infos sobre as ciclovias? https://www.google.com.br/maps/@-25.4951166,-49.2897982,11z/data=!5m1!1e3?hl=fr
- não reconheço o formato dos arquivos dentro do zip. Você pode nos informar que tipo de arquivo são e se tem uma documentação para usar eles?

Obrigado.

**Comment by brunoglara** [comment]
Pelo que conversei com pessoal do IPPUC é possível converter para formato do google, mas não passaram maiores detalhes. Comentaram que tem algumas informações dos arquivos no final da página http://ippuc.org.br/geodownloads/geo.htm

**Comment by thierrydelbart** [comment]
Li no final mas não ajuda. 
Você pode ver com eles como converter paa o formato do google? e também perguntar quais são os formatos atuais?

**Comment by biketrooper** [comment]
Formato atual: [Shapefile](https://en.wikipedia.org/wiki/Shapefile)

Testando [OGRE](https://ogre.adc4gis.com/)

**Comment by thierrydelbart** [comment]
Ok! Com OGRE conseguimos converter o ZIP em GeoJSON !!! Great!
Achei também este projeto: https://github.com/substack/shp2json

**Comment by thierrydelbart** [comment]
@biketrooper : você acha que a gente tem bastante informações ai para avançar? na minha opinião podemos sim.

**Comment by biketrooper** [comment]
[HTML5 Shapefile to GeoJSON Converter](http://techslides.com/demos/mapping/shapefile-geojson-converter.html)

**Comment by biketrooper** [comment]
[shp2geojson.js](https://github.com/gipong/shp2geojson.js)

[Demo](http://gipong.github.io/shp2geojson.js/)

**Comment by biketrooper** [comment]
@Thithi32 agora é fazer as conversões (https://github.com/gipong/shp2geojson.js) e testar (http://geojson.io/) até as ficarem corretas. \* Pelo que verifiquei até agora, não está 100%

**Comment by thierrydelbart** [comment]
Sim mas isso ta nas nossas mãos.

@brunoglara você pode verificar/confirmar que os links são persistantes:
http://ippuc.org.br/geodownloads/SHAPES/CICLOVIA_OFICIAL.zip
http://ippuc.org.br/geodownloads/SHAPES/CICLORROTA.zip

**Comment by brunoglara** [comment]
@Thithi32  não entendi o que confirmar?

**Comment by thierrydelbart** [comment]
@brunoglara que podemos usar esses endereços sem medo deles mudarem os arquivos cada dois meses.
