### ISSUE TITLE
GED - Acesso aos dados dos alunos, escolas, professores, etc

### ISSUE THREAD

**Issue by nerijunior** [CodeForCuritiba/dadosabertos_prefs#2]
O AlunuZ, mais específico no módulo do FICA, precisa das informações das escolas, alunos, professores, funcionários que estão relacionados ou fazem parte do processo de proteção e comunicação do aluno ausente.

Quantos mais dados puderem ser disponíveis melhor, sei que isso pode envolver informações privativas, mas assumo a responsabilidade dos dados de acesso e termos de sigílo das informações.

**Comment by thierrydelbart** [comment]
@nerijunior vc pode ficar mais claro sobre os dados que vocês precisam?

**Comment by nerijunior** [comment]
Todos os dados que conseguirem dos alunos, o GED tem muitas informações, eu mesmo não tenho conhecimento de todas, mas precisamos de todo tipo de informação possível para melhorar o cadastro dos alunos e pensar em medidas de proteção para os mesmos.

**Comment by thierrydelbart** [comment]
Ok espero que isso sega sufficiente. Eu encaminho.

**Comment by thierrydelbart** [comment]
Pedido desatualizado
