### ISSUE TITLE
Entrar em contato com os dados abertos da Cámara dos vereadores.

### ISSUE THREAD

**Issue by thierrydelbart** [CodeForCuritiba/dadosabertos_prefs#8]
a ideia era alguma forma mais fácil de obter estes dados.
http://www.cmc.pr.gov.br/wspl/system/LogonForm.do

**Comment by murilowlima** [comment]
Atualmente o sistema da câmara não permite automatização da busca de dados. Gostaríamos de uma forma de fazer integração com os dados da atividade parlamentar da câmara (dados de proposições, tramitação, dados de vereadores, etc.). Desta forma poderíamos criar aplicações de forma mais fácil. 

Um exemplo de integração que realizamos foi com o da câmara federal, que está aqui: http://www.camara.gov.br/SitCamaraWS/Proposicoes.asmx

**Comment by thierrydelbart** [comment]
@murilowlima a prefeitura não tem contato com a cámara
